name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - uses: Project-Env/project-env-github-action@v1.2.0
        with:
          cli-version: '3.4.0'
      - run: mvn -B -s etc/m2/settings-ci.xml verify
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}